const q=(s)=>document.querySelector(s),qa=(s)=>document.querySelectorAll(s),reveal=qa(".reveal"),btn=q("#theme-toggle"),langSel=q("#language-select"),viewsCount=q("#views-count");
const t={
en:{controls:{languageLabel:"Language",darkMode:"Dark Mode",lightMode:"Light Mode",profile:"Profile"},hero:{eyebrow:"Aspiring Web Developer / Content Creator",title:"Born to Code",text:"because of faith, it will happen Matthew 9:29",primaryCta:"View Projects",secondaryCta:"Explore Skills",status:"Open to growth-focused opportunities",locationLabel:"Location",locationValue:"Kigali, Rwanda",focusLabel:"Focus Areas",focus1:"Frontend and backend web fundamentals",focus2:"Automation and AI-assisted workflows",focus3:"Educational and niche digital content"},summary:{tag:"Summary",title:"Professional direction",body:"Aspiring web developer and content creator focused on building digital projects, learning modern technologies, and growing online platforms. Interested in software development, automation, and educational tech content."},skills:{tag:"Skills",title:"Core tools and foundations",item1:"HTML",item2:"CSS",item3:"JavaScript",item4:"Python",item5:"Django",item6:"MySQL",item7:"Java",item8:"C++",item9:"Web Development Fundamentals",item10:"Video Editing Basics",item11:"Content Creation"},projects:{tag:"Projects",title:"Current work and experiments",modznestLabel:"In Progress",modznestBody:"A website project focused on tools and app-related utilities, with room to grow into a practical platform for users interested in custom tools.",experimentsLabel:"Practice",experimentsTitle:"Personal Web Experiments",experimentsBody:"Ongoing frontend and backend practice projects used to sharpen development skills and test new ideas."},channels:{tag:"Channels",title:"Content creation ecosystem",seniorMiner:"Crypto-focused content and insights.",vietaMiner:"Tech educational content.",theTraveler:"Travel experiences and exploration stories.",moneyMiner:"Finance, online income, and growth-focused topics."},learning:{tag:"Learning",title:"What is being improved now",item1:"Learning machine learning",item2:"Practicing coding and web development consistently",item3:"Exercising with AI tools and systems",item4:"Exploring content creation"},goal:{tag:"Long-Term Goal",title:"Enlighten the world through digital work",body:"The main objective is to build systems that solve real problems through software development, digital platforms, and content creation."}},
rw:{controls:{languageLabel:"Ururimi",darkMode:"Uburyo bw'ijoro",lightMode:"Uburyo bw'urumuri",profile:"Umwirondoro"},hero:{eyebrow:"Ushaka kuba umutekinisiye wa webu / Umuremyi w'ibirimo",title:"Yavukiye gukoda",text:"kubera ukwizera, bizaba Matayo 9:29",primaryCta:"Reba Imishinga",secondaryCta:"Reba Ubumenyi",status:"Yiteguye amahirwe yo gukura",locationLabel:"Aho abarizwa",locationValue:"Kigali, Rwanda",focusLabel:"Ibyibandwaho",focus1:"Ishingiro rya frontend na backend",focus2:"Automation n'uburyo bukoresha AI",focus3:"Ibirimo byigisha n'ibirimo byihariye bya digitali"},summary:{tag:"Incamake",title:"Icyerekezo cy'umwuga",body:"Umusore ushaka kuba web developer n'umuremyi w'ibirimo, yibanda ku kubaka imishinga ya digitali, kwiga ikoranabuhanga rigezweho, no guteza imbere imbuga zo kuri interineti. Ashishikajwe na software development, automation, n'ibirimo by'ikoranabuhanga byigisha."},skills:{tag:"Ubumenyi",title:"Ibikoresho n'ishingiro",item1:"HTML",item2:"CSS",item3:"JavaScript",item4:"Python",item5:"Django",item6:"MySQL",item7:"Java",item8:"C++",item9:"Ishingiro rya Web Development",item10:"Ishingiro rya Video Editing",item11:"Gukora Ibirimo"},projects:{tag:"Imishinga",title:"Ibikorwa biri gukorwa n'igerageza",modznestLabel:"Biracyakorwa",modznestBody:"Umushinga w'urubuga wibanda ku bikoresho byihariye n'ibijyanye na apps, ushobora gukuramo urubuga rufasha abakoresha bashaka ibikoresho byihariye.",experimentsLabel:"Kwimenyereza",experimentsTitle:"Ubugerageza bwa Webu bwite",experimentsBody:"Imishinga ya frontend na backend ikomeje gufasha gukaza ubumenyi no kugerageza ibitekerezo bishya."},channels:{tag:"Imiyoboro",title:"Uburyo bwo gukora ibirimo",seniorMiner:"Ibirimo byibanda kuri crypto n'ibitekerezo biyireba.",vietaMiner:"Ibirimo byigisha tech.",theTraveler:"Ubuhamya bw'ingendo n'inkuru zo gutembera.",moneyMiner:"Imari, kwinjiza amafaranga kuri interineti, n'ibindi byerekeranye n'iterambere."},learning:{tag:"Kwiga",title:"Ibirimo kunozwa ubu",item1:"Kwiga machine learning",item2:"Kwimenyereza gukoda no gukora webu buri gihe",item3:"Gukoresha ibikoresho n'uburyo bwa AI",item4:"Gushakashaka uburyo bwo gukora ibirimo"},goal:{tag:"Intego y'igihe kirekire",title:"Kumurikira isi binyuze mu murimo wa digitali",body:"Intego nyamukuru ni ukubaka uburyo bukora ibibazo bifatika binyuze mu gukora software, imbuga za digitali, no gukora ibirimo."}},
fr:{controls:{languageLabel:"Langue",darkMode:"Mode sombre",lightMode:"Mode clair",profile:"Profil"},hero:{eyebrow:"Developpeur web en devenir / Createur de contenu",title:"Né pour coder",text:"par la foi, cela arrivera Matthieu 9:29",primaryCta:"Voir les projets",secondaryCta:"Voir les competences",status:"Ouvert aux opportunites de progression",locationLabel:"Lieu",locationValue:"Kigali, Rwanda",focusLabel:"Domaines cles",focus1:"Fondamentaux frontend et backend",focus2:"Automatisation et flux assistes par l'IA",focus3:"Contenu educatif et numerique de niche"},summary:{tag:"Resume",title:"Orientation professionnelle",body:"Developpeur web et createur de contenu en devenir, axe sur la creation de projets numeriques, l'apprentissage des technologies modernes et la croissance des plateformes en ligne. Interet pour le developpement logiciel, l'automatisation et le contenu educatif technologique."},skills:{tag:"Competences",title:"Outils et bases",item1:"HTML",item2:"CSS",item3:"JavaScript",item4:"Python",item5:"Django",item6:"MySQL",item7:"Java",item8:"C++",item9:"Fondamentaux du developpement web",item10:"Bases du montage video",item11:"Creation de contenu"},projects:{tag:"Projets",title:"Travaux en cours et experimentations",modznestLabel:"En cours",modznestBody:"Projet de site axe sur les outils et les utilitaires lies aux applications, avec un potentiel d'evolution vers une plateforme pratique pour les utilisateurs.",experimentsLabel:"Pratique",experimentsTitle:"Experiences web personnelles",experimentsBody:"Projets pratiques frontend et backend pour renforcer les competences et tester de nouvelles idees."},channels:{tag:"Chaines",title:"Ecosysteme de creation de contenu",seniorMiner:"Contenu et analyses axes sur la crypto.",vietaMiner:"Contenu educatif sur la technologie.",theTraveler:"Experiences de voyage et recits d'exploration.",moneyMiner:"Finance, revenus en ligne et sujets de croissance."},learning:{tag:"Apprentissage",title:"Ce qui est ameliore maintenant",item1:"Apprendre le machine learning",item2:"Pratiquer le codage et le developpement web regulierement",item3:"S'exercer avec les outils et systemes d'IA",item4:"Explorer la creation de contenu"},goal:{tag:"Objectif a long terme",title:"Eclairer le monde par le travail numerique",body:"L'objectif principal est de construire des systemes qui resolvent des problemes reels grace au developpement de logiciels, aux plateformes numeriques et a la creation de contenu."}},
sw:{controls:{languageLabel:"Lugha",darkMode:"Hali ya giza",lightMode:"Hali ya mwanga",profile:"Wasifu"},hero:{eyebrow:"Msanidi wa wavuti anayekua / Mtayarishaji wa maudhui",title:"Alizaliwa kukoda",text:"kwa sababu ya imani, itatokea Mathayo 9:29",primaryCta:"Tazama Miradi",secondaryCta:"Chunguza Ujuzi",status:"Yupo wazi kwa fursa za ukuaji",locationLabel:"Mahali",locationValue:"Kigali, Rwanda",focusLabel:"Maeneo ya msingi",focus1:"Misingi ya frontend na backend",focus2:"Automation na mifumo inayosaidiwa na AI",focus3:"Maudhui ya kielimu na ya kidijitali ya kipekee"},summary:{tag:"Muhtasari",title:"Mwelekeo wa kitaaluma",body:"Msanidi wa wavuti anayeanza na mtayarishaji wa maudhui anayelenga kujenga miradi ya kidijitali, kujifunza teknolojia za kisasa, na kukuza majukwaa ya mtandaoni. Anavutiwa na maendeleo ya programu, automation, na maudhui ya teknolojia ya kielimu."},skills:{tag:"Ujuzi",title:"Zana na misingi",item1:"HTML",item2:"CSS",item3:"JavaScript",item4:"Python",item5:"Django",item6:"MySQL",item7:"Java",item8:"C++",item9:"Misingi ya Web Development",item10:"Misingi ya Video Editing",item11:"Utengenezaji wa Maudhui"},projects:{tag:"Miradi",title:"Kazi ya sasa na majaribio",modznestLabel:"Inaendelea",modznestBody:"Mradi wa tovuti unaolenga zana na huduma zinazohusiana na programu, ukiwa na nafasi ya kukua kuwa jukwaa la vitendo kwa watumiaji.",experimentsLabel:"Mazoezi",experimentsTitle:"Majaribio binafsi ya wavuti",experimentsBody:"Miradi ya mazoezi ya frontend na backend inayoendelea kusaidiana kuimarisha ujuzi na kujaribu mawazo mapya."},channels:{tag:"Chaneli",title:"Mfumo wa maudhui",seniorMiner:"Maudhui na maarifa yanayolenga crypto.",vietaMiner:"Maudhui ya elimu ya tech.",theTraveler:"Uzoefu wa safari na simulizi za kutembelea.",moneyMiner:"Fedha, kipato cha mtandaoni, na mada za ukuaji."},learning:{tag:"Kujifunza",title:"Kinachoboreshwa sasa",item1:"Kujifunza machine learning",item2:"Kufanya mazoezi ya kukoda na kukuza wavuti mara kwa mara",item3:"Kufanya mazoezi na zana na mifumo ya AI",item4:"Kuchunguza utengenezaji wa maudhui"},goal:{tag:"Lengo la Muda Mrefu",title:"Kuifahamisha dunia kupitia kazi ya kidijitali",body:"Lengo kuu ni kujenga mifumo inayotatua matatizo ya kweli kupitia maendeleo ya programu, majukwaa ya kidijitali, na utengenezaji wa maudhui."}},
es:{controls:{languageLabel:"Idioma",darkMode:"Modo oscuro",lightMode:"Modo clair",profile:"Perfil"},hero:{eyebrow:"Desarrollador web en crecimiento / Creador de contenido",title:"Nacido para programar",text:"por la fe, sucedera Mateo 9:29",primaryCta:"Ver proyectos",secondaryCta:"Explorar habilidades",status:"Abierto a oportunidades de crecimiento",locationLabel:"Ubicacion",locationValue:"Kigali, Rwanda",focusLabel:"Areas de enfoque",focus1:"Fundamentos de frontend y backend",focus2:"Automatizacion y flujos asistidos por IA",focus3:"Contenido educativo y digital de nicho"},summary:{tag:"Resumen",title:"Direccion profesional",body:"Desarrollador web y creador de contenido en crecimiento, enfocado en construir proyectos digitales, aprender tecnologias modernas y hacer crecer plataformas en linea. Interesado en desarrollo de software, automatizacion y contenido tecnologico educativo."},skills:{tag:"Habilidades",title:"Herramientas y bases",item1:"HTML",item2:"CSS",item3:"JavaScript",item4:"Python",item5:"Django",item6:"MySQL",item7:"Java",item8:"C++",item9:"Fundamentos de desarrollo web",item10:"Conceptos basicos de edicion de video",item11:"Creacion de contenido"},projects:{tag:"Proyectos",title:"Trabajo actual y experimentos",modznestLabel:"En progreso",modznestBody:"Proyecto de sitio web enfocado en herramientas y utilidades relacionadas con aplicaciones, con potencial para crecer como plataforma practica.",experimentsLabel:"Practica",experimentsTitle:"Experimentos web personales",experimentsBody:"Proyectos continuos de practica frontend y backend para fortalecer habilidades y probar nuevas ideas."},channels:{tag:"Canales",title:"Ecosistema de creacion de contenido",seniorMiner:"Contenido e ideas centradas en crypto.",vietaMiner:"Contenido educativo sobre tecnologia.",theTraveler:"Experiencias de viaje e historias de exploracion.",moneyMiner:"Finanzas, ingresos en linea y temas de crecimiento."},learning:{tag:"Aprendizaje",title:"Lo que se esta mejorando ahora",item1:"Aprender machine learning",item2:"Practicar programacion y desarrollo web constantemente",item3:"Ejercitarse con herramientas y sistemas de IA",item4:"Explorar la creacion de contenido"},goal:{tag:"Meta a largo plazo",title:"Iluminar el mundo a traves del trabajo digital",body:"El objetivo principal es construir sistemas que resuelvan problemas reales a traves del desarrollo de software, plataformas digitales y creacion de contenido."}},
de:{controls:{languageLabel:"Sprache",darkMode:"Dunkelmodus",lightMode:"Hellmodus",profile:"Profil"},hero:{eyebrow:"Angehender Webentwickler / Content Creator",title:"Geboren zum Programmieren",text:"durch den Glauben wird es geschehen Matthaus 9:29",primaryCta:"Projekte ansehen",secondaryCta:"Fahigkeiten ansehen",status:"Offen fur wachstumsorientierte Chancen",locationLabel:"Standort",locationValue:"Kigali, Rwanda",focusLabel:"Schwerpunkte",focus1:"Frontend- und Backend-Grundlagen",focus2:"Automatisierung und KI-gestutzte Workflows",focus3:"Lehrreiche und spezialisierte digitale Inhalte"},summary:{tag:"Zusammenfassung",title:"Berufliche Ausrichtung",body:"Angehender Webentwickler und Content Creator mit Fokus auf digitale Projekte, moderne Technologien und den Ausbau von Online-Plattformen. Interesse an Softwareentwicklung, Automatisierung und lehrreichen Tech-Inhalten."},skills:{tag:"Fahigkeiten",title:"Werkzeuge und Grundlagen",item1:"HTML",item2:"CSS",item3:"JavaScript",item4:"Python",item5:"Django",item6:"MySQL",item7:"Java",item8:"C++",item9:"Grundlagen der Webentwicklung",item10:"Grundlagen der Videobearbeitung",item11:"Content-Erstellung"},projects:{tag:"Projekte",title:"Aktuelle Arbeit und Experimente",modznestLabel:"In Arbeit",modznestBody:"Ein Website-Projekt zu Tools und App-bezogenen Utilities mit Potenzial fur eine praktische Plattform fur Nutzer.",experimentsLabel:"Praxis",experimentsTitle:"Personliche Web-Experimente",experimentsBody:"Laufende Frontend- und Backend-Ubungsprojekte zur Verbesserung der Entwicklungsfahigkeiten und zum Test neuer Ideen."},channels:{tag:"Kanale",title:"Content-Okosystem",seniorMiner:"Krypto-fokussierte Inhalte und Einblicke.",vietaMiner:"Lehrreiche Inhalte zu Tech.",theTraveler:"Reiseerfahrungen und Entdeckungsgeschichten.",moneyMiner:"Finanzen, Online-Einkommen und Wachstumsthemen."},learning:{tag:"Lernen",title:"Was gerade verbessert wird",item1:"Maschinelles Lernen lernen",item2:"Regelmassiges Uben von Programmierung und Webentwicklung",item3:"Uben mit KI-Werkzeugen und -Systemen",item4:"Erkundung der Content-Erstellung"},goal:{tag:"Langfristiges Ziel",title:"Die Welt durch digitale Arbeit erleuchten",body:"Das Hauptziel ist der Aufbau von Systemen, die reale Probleme durch Softwareentwicklung, digitale Plattformen und Content-Erstellung losen."}},
ar:{controls:{languageLabel:"اللغة",darkMode:"الوضع الداكن",lightMode:"الوضع الفاتح",profile:"الملف"},hero:{eyebrow:"مطور ويب طموح / صانع محتوى",title:"ولد للبرمجة",text:"بالايمان، سيحدث ذلك متى 9:29",primaryCta:"عرض المشاريع",secondaryCta:"استكشاف المهارات",status:"منفتح على فرص النمو",locationLabel:"الموقع",locationValue:"كيغالي، رواندا",focusLabel:"مجالات التركيز",focus1:"اساسيات الواجهة الامامية والخلفية",focus2:"الاتمتة وسير العمل المدعوم بالذكاء الاصطناعي",focus3:"المحتوى التعليمي والمحتوى الرقمي المتخصص"},summary:{tag:"الملخص",title:"الاتجاه المهني",body:"مطور ويب وصانع محتوى طموح يركز على بناء المشاريع الرقمية وتعلم التقنيات الحديثة وتنمية المنصات عبر الانترنت. مهتم بتطوير البرمجيات والاتمتة والمحتوى التقني التعليمي."},skills:{tag:"المهارات",title:"الادوات والاساسيات",item1:"HTML",item2:"CSS",item3:"JavaScript",item4:"Python",item5:"Django",item6:"MySQL",item7:"Java",item8:"C++",item9:"اساسيات تطوير الويب",item10:"اساسيات تحرير الفيديو",item11:"صناعة المحتوى"},projects:{tag:"المشاريع",title:"العمل الحالي والتجارب",modznestLabel:"قيد التنفيذ",modznestBody:"مشروع موقع يركز على الادوات والادوات المرتبطة بالتطبيقات، مع امكانية التطور الى منصة عملية للمستخدمين.",experimentsLabel:"تدريب",experimentsTitle:"تجارب ويب شخصية",experimentsBody:"مشاريع تدريب مستمرة في الواجهة الامامية والخلفية لتحسين المهارات وتجربة افكار جديدة."},channels:{tag:"القنوات",title:"منظومة صناعة المحتوى",seniorMiner:"محتوى ورؤى تركز على العملات الرقمية.",vietaMiner:"محتوى تعليمي في التقنية.",theTraveler:"تجارب سفر وقصص استكشاف.",moneyMiner:"المال والدخل عبر الانترنت وموضوعات النمو."},learning:{tag:"التعلم",title:"ما يتم تحسينه حاليا",item1:"تعلم تعلم الالة",item2:"ممارسة البرمجة وتطوير الويب باستمرار",item3:"التدرب على ادوات وانظمة الذكاء الاصطناعي",item4:"استكشاف صناعة المحتوى"},goal:{tag:"الهدف طويل المدى",title:"تنوير العالم من خلال العمل الرقمي",body:"الهدف الرئيسي هو بناء انظمة تحل مشاكل حقيقية من خلال تطوير البرمجيات والمنصات الرقمية وصناعة المحتوى."}}
};
const obs=new IntersectionObserver((e)=>e.forEach((x)=>{if(x.isIntersecting){x.target.classList.add("is-visible");obs.unobserve(x.target);}}),{threshold:.16,rootMargin:"0px 0px -30px 0px"});
reveal.forEach((n,i)=>{n.style.transitionDelay=`${i*80}ms`;obs.observe(n);});
const gv=(p,l)=>p.split(".").reduce((a,k)=>a&&a[k],t[l]);
let typeTimer, isDeleting = false, txtIdx = 0;
function typeLoop(el, text) {
  if (typeTimer) clearTimeout(typeTimer);
  const fullTxt = text;
  if (isDeleting) {
    el.textContent = fullTxt.substring(0, txtIdx - 1);
    txtIdx--;
  } else {
    el.textContent = fullTxt.substring(0, txtIdx + 1);
    txtIdx++;
  }
  let typeSpeed = isDeleting ? 60 : 120;
  if (!isDeleting && txtIdx === fullTxt.length) {
    typeSpeed = 2500;
    isDeleting = true;
    el.classList.remove("typing-active");
  } else if (isDeleting && txtIdx === 0) {
    isDeleting = false;
    typeSpeed = 500;
  }
  if (txtIdx > 0 || !isDeleting) el.classList.add("typing-active");
  typeTimer = setTimeout(() => typeLoop(el, text), typeSpeed);
}
function setThemeLabel(theme,lang){const a=lang||langSel.value||"en";btn.setAttribute("aria-label",t[a].controls[theme==="dark"?"lightMode":"darkMode"]);}
function setLang(lang){
  document.documentElement.lang=lang;
  document.documentElement.dir=lang==="ar"?"rtl":"ltr";
  qa("[data-i18n]").forEach((n)=>{
    const v=gv(n.dataset.i18n,lang)||gv(n.dataset.i18n,"en");
    if(v) {
      if (n.dataset.i18n === "hero.title") {
        txtIdx = 0; isDeleting = false;
        typeLoop(n, v);
      } else {
        n.textContent=v;
      }
    }
  });
  localStorage.setItem("resume-language",lang);
  setThemeLabel(document.body.dataset.theme||"light",lang);
}
function setTheme(theme){document.body.dataset.theme=theme;localStorage.setItem("resume-theme",theme);setThemeLabel(theme);}
function setViews(){if(!viewsCount)return;const key="resume-site-views";const total=Number(localStorage.getItem(key)||0)+1;localStorage.setItem(key,String(total));viewsCount.textContent=total.toLocaleString();}
const savedLang=localStorage.getItem("resume-language")||"en",savedTheme=localStorage.getItem("resume-theme")||"light";
langSel.value=savedLang;setLang(savedLang);setTheme(savedTheme);
setViews();
langSel.addEventListener("change",(e)=>setLang(e.target.value));
btn.addEventListener("click",()=>setTheme(document.body.dataset.theme==="dark"?"light":"dark"));
